import type { Category, Product, Testimonial } from "./types";

/**
 * Mock storefront data. Swap these arrays for Supabase queries later —
 * the shapes match `types.ts` so components won't need to change.
 */

export const categories: Category[] = [
  {
    id: "c1",
    slug: "crochet-flowers",
    name: "Crochet Flowers",
    description: "Everlasting blooms that never wilt.",
    icon: "🌸",
    productCount: 24,
    accent: "pink",
  },
  {
    id: "c2",
    slug: "bouquets",
    name: "Bouquets",
    description: "Handtied arrangements made to last.",
    icon: "💐",
    productCount: 16,
    accent: "sage",
  },
  {
    id: "c3",
    slug: "plushies",
    name: "Plushies",
    description: "Soft, huggable amigurumi friends.",
    icon: "🧸",
    productCount: 31,
    accent: "brown",
  },
  {
    id: "c4",
    slug: "keychains",
    name: "Keychains",
    description: "Tiny charms with big personality.",
    icon: "🔑",
    productCount: 42,
    accent: "pink",
  },
  {
    id: "c5",
    slug: "home-decor",
    name: "Home Décor",
    description: "Cosy touches for every corner.",
    icon: "🏡",
    productCount: 19,
    accent: "sage",
  },
  {
    id: "c6",
    slug: "baby-gifts",
    name: "Baby Gifts",
    description: "Gentle keepsakes for little ones.",
    icon: "🍼",
    productCount: 22,
    accent: "brown",
  },
  {
    id: "c7",
    slug: "seasonal",
    name: "Seasonal Collection",
    description: "Limited pieces for every occasion.",
    icon: "🍂",
    productCount: 14,
    accent: "pink",
  },
  {
    id: "c8",
    slug: "custom-orders",
    name: "Custom Orders",
    description: "Dreamed up by you, crafted by us.",
    icon: "✨",
    productCount: 0,
    accent: "sage",
  },
  {
    id: "c9",
    slug: "gift-sets",
    name: "Gift Sets",
    description: "Beautifully bundled and ready to give.",
    icon: "🎁",
    productCount: 11,
    accent: "brown",
  },
  {
    id: "c10",
    slug: "accessories",
    name: "Accessories",
    description: "Wearable handmade details.",
    icon: "👜",
    productCount: 27,
    accent: "pink",
  },
];

export const products: Product[] = [
  {
    id: "p1",
    slug: "blush-rose-bouquet",
    name: "Blush Rose Bouquet",
    categorySlug: "bouquets",
    price: 68,
    salePrice: 54,
    currency: "USD",
    rating: 4.9,
    reviewCount: 10,
    images: [{ url: "", alt: "Blush rose crochet bouquet" }],
    swatch: "linear-gradient(135deg,#f3d7d2,#d3a7a1,#c0857e)",
    colors: ["Blush", "Ivory", "Sage"],
    materials: ["Premium cotton yarn", "Floral wire"],
    isBestSeller: true,
    customizable: true,
    inStock: true,
    shortDescription: "A dozen everlasting roses, hand-tied in soft blush.",
  },
  {
    id: "p2",
    slug: "honey-bear-plushie",
    name: "Honey the Bear",
    categorySlug: "plushies",
    price: 42,
    currency: "USD",
    rating: 5.0,
    reviewCount: 17,
    images: [{ url: "", alt: "Honey bear amigurumi plushie" }],
    swatch: "linear-gradient(135deg,#e6dac6,#cbb794,#9c7f5a)",
    colors: ["Honey", "Caramel", "Cream"],
    materials: ["Organic cotton", "Hypoallergenic filling"],
    isBestSeller: true,
    isNew: true,
    customizable: true,
    inStock: true,
    shortDescription: "A cuddly amigurumi bear with an embroidered smile.",
  },
  {
    id: "p3",
    slug: "sage-tulip-trio",
    name: "Sage Tulip Trio",
    categorySlug: "crochet-flowers",
    price: 24,
    currency: "USD",
    rating: 4.8,
    reviewCount: 6,
    images: [{ url: "", alt: "Three sage tulips in crochet" }],
    swatch: "linear-gradient(135deg,#d6e0cb,#8fa57e,#6e8560)",
    colors: ["Sage", "Sand", "Blush"],
    materials: ["Cotton yarn", "Bendable stems"],
    isBestSeller: true,
    customizable: true,
    inStock: true,
    shortDescription: "Three delicate tulips that bloom forever.",
  },
  {
    id: "p4",
    slug: "cloud-baby-mobile",
    name: "Cloud Baby Mobile",
    categorySlug: "baby-gifts",
    price: 58,
    currency: "USD",
    rating: 4.9,
    reviewCount: 4,
    images: [{ url: "", alt: "Crochet cloud nursery mobile" }],
    swatch: "linear-gradient(135deg,#faf8f4,#e6dac6,#d3a7a1)",
    colors: ["Cloud", "Blush", "Sky"],
    materials: ["Soft cotton", "Birch hoop"],
    isBestSeller: true,
    isNew: true,
    customizable: true,
    inStock: true,
    shortDescription: "A dreamy nursery mobile of clouds and stars.",
  },
  {
    id: "p5",
    slug: "mini-strawberry-keychain",
    name: "Mini Strawberry Keychain",
    categorySlug: "keychains",
    price: 12,
    currency: "USD",
    rating: 4.7,
    reviewCount: 25,
    images: [{ url: "", alt: "Strawberry crochet keychain" }],
    swatch: "linear-gradient(135deg,#f3d7d2,#c0857e,#8fa57e)",
    colors: ["Berry", "Sage"],
    materials: ["Cotton yarn", "Gold clasp"],
    isBestSeller: true,
    customizable: false,
    inStock: true,
    shortDescription: "A pocket-sized berry charm for keys or bags.",
  },
  {
    id: "p6",
    slug: "dusty-pink-tote",
    name: "Dusty Pink Market Tote",
    categorySlug: "accessories",
    price: 46,
    currency: "USD",
    rating: 4.8,
    reviewCount: 7,
    images: [{ url: "", alt: "Dusty pink crochet tote bag" }],
    swatch: "linear-gradient(135deg,#e9c9c4,#d3a7a1,#c0857e)",
    colors: ["Dusty Pink", "Cream"],
    materials: ["Recycled cotton cord"],
    isBestSeller: true,
    customizable: true,
    inStock: true,
    shortDescription: "A roomy, hand-stitched tote for slow mornings.",
  },
  {
    id: "p7",
    slug: "autumn-pumpkin-set",
    name: "Autumn Pumpkin Set",
    categorySlug: "seasonal",
    price: 34,
    currency: "USD",
    rating: 4.9,
    reviewCount: 5,
    images: [{ url: "", alt: "Set of crochet autumn pumpkins" }],
    swatch: "linear-gradient(135deg,#e6dac6,#cbb794,#c0857e)",
    colors: ["Rust", "Sand", "Sage"],
    materials: ["Cotton yarn", "Cinnamon stem"],
    isBestSeller: true,
    isNew: true,
    customizable: true,
    inStock: true,
    shortDescription: "A trio of cosy pumpkins for the mantel.",
  },
  {
    id: "p8",
    slug: "lavender-coaster-set",
    name: "Lavender Coaster Set",
    categorySlug: "home-decor",
    price: 28,
    currency: "USD",
    rating: 4.7,
    reviewCount: 3,
    images: [{ url: "", alt: "Set of four lavender crochet coasters" }],
    swatch: "linear-gradient(135deg,#f3ece0,#d6c3a5,#8fa57e)",
    colors: ["Lavender", "Cream", "Sage"],
    materials: ["Cotton yarn"],
    isBestSeller: true,
    customizable: false,
    inStock: true,
    shortDescription: "Four scalloped coasters to dress any table.",
  },
  {
    id: "p9",
    slug: "peony-garden-bouquet",
    name: "Peony Garden Bouquet",
    categorySlug: "bouquets",
    price: 82,
    currency: "USD",
    rating: 4.9,
    reviewCount: 3,
    images: [{ url: "", alt: "Peony crochet bouquet" }],
    swatch: "linear-gradient(135deg,#f3d7d2,#e9c9c4,#8fa57e)",
    colors: ["Blush", "Ivory", "Sage"],
    materials: ["Premium cotton yarn", "Floral wire"],
    customizable: true,
    isNew: true,
    inStock: true,
    shortDescription: "Lush peonies and greenery, hand-tied to order.",
  },
  {
    id: "p10",
    slug: "bunny-amigurumi",
    name: "Willow the Bunny",
    categorySlug: "plushies",
    price: 38,
    currency: "USD",
    rating: 4.9,
    reviewCount: 13,
    images: [{ url: "", alt: "Bunny amigurumi" }],
    swatch: "linear-gradient(135deg,#faf8f4,#e6dac6,#d3a7a1)",
    colors: ["Cream", "Blush"],
    materials: ["Organic cotton", "Hypoallergenic filling"],
    customizable: true,
    inStock: true,
    shortDescription: "A floppy-eared bunny with a hand-stitched face.",
  },
  {
    id: "p11",
    slug: "daisy-hair-clips",
    name: "Daisy Hair Clip Set",
    categorySlug: "accessories",
    price: 16,
    currency: "USD",
    rating: 4.6,
    reviewCount: 7,
    images: [{ url: "", alt: "Daisy crochet hair clips" }],
    swatch: "linear-gradient(135deg,#faf8f4,#f3ece0,#cbb794)",
    colors: ["Ivory", "Butter"],
    materials: ["Cotton yarn", "Metal clips"],
    customizable: false,
    inStock: true,
    shortDescription: "A pair of cheerful daisies for everyday wear.",
  },
  {
    id: "p12",
    slug: "cozy-plant-pot-cover",
    name: "Cozy Plant Pot Cover",
    categorySlug: "home-decor",
    price: 22,
    currency: "USD",
    rating: 4.7,
    reviewCount: 3,
    images: [{ url: "", alt: "Crochet plant pot cover" }],
    swatch: "linear-gradient(135deg,#d6e0cb,#8fa57e,#6e8560)",
    colors: ["Sage", "Sand"],
    materials: ["Cotton yarn"],
    customizable: true,
    inStock: true,
    shortDescription: "Dress up any planter with a soft knit cover.",
  },
  {
    id: "p13",
    slug: "newborn-booties",
    name: "Newborn Booties",
    categorySlug: "baby-gifts",
    price: 18,
    currency: "USD",
    rating: 5.0,
    reviewCount: 10,
    images: [{ url: "", alt: "Crochet newborn booties" }],
    swatch: "linear-gradient(135deg,#faf8f4,#f3d7d2,#d3a7a1)",
    colors: ["Blush", "Cloud", "Butter"],
    materials: ["Soft baby cotton"],
    customizable: true,
    isNew: true,
    inStock: true,
    shortDescription: "The softest first booties, made to be treasured.",
  },
  {
    id: "p14",
    slug: "sunflower-single-stem",
    name: "Sunflower Single Stem",
    categorySlug: "crochet-flowers",
    price: 14,
    currency: "USD",
    rating: 4.8,
    reviewCount: 5,
    images: [{ url: "", alt: "Single crochet sunflower stem" }],
    swatch: "linear-gradient(135deg,#f0e2b8,#cbb794,#8fa57e)",
    colors: ["Golden", "Sage"],
    materials: ["Cotton yarn", "Bendable stem"],
    customizable: false,
    inStock: false,
    shortDescription: "One sunny bloom to brighten any vase.",
  },
  {
    id: "p15",
    slug: "holiday-ornament-set",
    name: "Holiday Ornament Set",
    categorySlug: "seasonal",
    price: 30,
    currency: "USD",
    rating: 4.9,
    reviewCount: 4,
    images: [{ url: "", alt: "Crochet holiday ornaments" }],
    swatch: "linear-gradient(135deg,#f3d7d2,#c0857e,#6e8560)",
    colors: ["Berry", "Sage", "Cream"],
    materials: ["Cotton yarn"],
    customizable: true,
    inStock: true,
    shortDescription: "A set of five heirloom ornaments for the tree.",
  },
  {
    id: "p16",
    slug: "self-care-gift-set",
    name: "Self-Care Gift Set",
    categorySlug: "gift-sets",
    price: 64,
    currency: "USD",
    rating: 4.9,
    reviewCount: 3,
    images: [{ url: "", alt: "Crochet self-care gift set" }],
    swatch: "linear-gradient(135deg,#e9c9c4,#d3a7a1,#8fa57e)",
    colors: ["Blush", "Sage"],
    materials: ["Cotton yarn", "Gift box"],
    customizable: true,
    isNew: true,
    inStock: true,
    shortDescription: "Coasters, a flower, and a keychain, beautifully boxed.",
  },
];

export const bestSellers = products.filter((p) => p.isBestSeller);
export const newArrivals = products.filter((p) => p.isNew);

export function getProductBySlug(slug: string) {
  return products.find((p) => p.slug === slug);
}

export function getCategoryBySlug(slug: string) {
  return categories.find((c) => c.slug === slug);
}

export function getRelatedProducts(product: Product, limit = 4) {
  return products
    .filter((p) => p.id !== product.id && p.categorySlug === product.categorySlug)
    .concat(products.filter((p) => p.categorySlug !== product.categorySlug))
    .slice(0, limit);
}

export const allColors = Array.from(
  new Set(products.flatMap((p) => p.colors)),
).sort();

export const testimonials: Testimonial[] = [
  {
    id: "t1",
    name: "Amelia R.",
    location: "London, UK",
    rating: 5,
    quote:
      "The bouquet arrived more beautiful than the photos. You can feel the love in every stitch — it's a keepsake I'll have forever.",
    verified: true,
    initials: "AR",
  },
  {
    id: "t2",
    name: "Sofia M.",
    location: "Dubai, UAE",
    rating: 5,
    quote:
      "I ordered a custom plushie for my daughter and the whole process felt so personal. The quality is genuinely luxurious.",
    verified: true,
    initials: "SM",
  },
  {
    id: "t3",
    name: "Hannah K.",
    location: "Toronto, CA",
    rating: 5,
    quote:
      "Gorgeous packaging, fast shipping, and the softest yarn. Nifty Needle has become my go-to for meaningful gifts.",
    verified: true,
    initials: "HK",
  },
];
